// src/tokens.js
export const semanticTokens = {
    colors: {

      primary: '#FF0000',
      secondary: '#28A745',
      contrast: '#333333',
      background: '#FFFFFF',
      textPrimary: '#333333',
      textSecondary: '#666666',
      disabledBackground: '#CCCCCC',
      disabledText: '#888888',
      disabledBackground: '#CCCCCC',
      hoverBackground: '#FFCCCC',
      newsletter: '#FFFF00',
      textPrimary: '#FFFFFF',
      textSecondary: '#000000',
      hoverBackground: '#FFCCCC',
      newsletter: '#FFFF00',
      toggleOff: '#BDBDBD',
      toggleOn: '#FF0000',
      modalOverlayLight: 'rgba(0, 0, 0, 0.5)',
      modalBackgroundLight: '#FFFFFF',
      modalOverlayDark: 'rgba(0, 0, 0, 0.8)',
      modalBackgroundDark: '#333333',
      tabActive: '#FF0000',
    tabInactive: '#FFFFFF',
    tabHover: '#FFCCCC',
    tabDisabled: '#CCCCCC',
    radioDefault: '#FFFFFF',
    radioChecked: '#FF0000',
    alertStandard: '#FF5C5C',
    alertSecondary: '#FFEDED',
    alertSuccess: '#DFF2D8',
    alertContrast: '#333333',
    radioDisabled: '#CCCCCC',
    radioCheckedDisabled: '#888888',
    dropdownBackground: '#FFFFFF',
    dropdownHover: '#F5F5F5',
    progressBarBackground: '#CCCCCC',
    progressBarForeground: '#FF0000',
    spinnerBackground: '#CCCCCC',
    spinnerForeground: '#FF0000',
    borderColor: '#000000',
    cardBackground: '#FFFFFF',
    cardBorder: '#E0E0E0',
    bannerStandard: '#FF5C5C',
    bannerSecondary: '#FFEDED',
    bannerContrast: '#333333',
    checkboxDefault: '#E0E0E0',
    checkboxChecked: '#FF0000',
    checkboxIndeterminate: '#FF0000',
    checkboxDisabled: '#BDBDBD',
    checkboxInvalid: '#FF0000',
    checkboxHover: '#757575',
      backgroundNewsletter: '#FFFD06',
      successPrimary: '#409F6B',
      successSecondary: '#D4EADE',
      brandPrimary: '#D9353B',
      brandSecondary: '#FF8286',
      redLight: '#FFEAEB',
      bgDark: '#262626',
      bgTertiary: '#BDBDBD',
      bgSecondary: '#F2F2F2',
      bg: '#FFFFFF',
      neutral300: '#262626',
      neutral200: '#BDBDBD',
      neutral100: '#F2F2F2',
      neutral000: '#FFFFFF',
      green200: '#409F6B',
      green100: '#D4EADE',
      yellow100: '#FFFD06',
      red100: '#FFEAEB',
      red200: '#FF8286',
      red300: '#D9353B',
    },
    fonts: {
      body: 'Helvetica, Arial, sans-serif',
      heading: 'Arial Black, sans-serif',
    },
    fontSizes: {
      h1: '64px',
      h2: '48px',
      h3: '32px',
      h4: '24px',
      h5: '20px',
      h6: '16px',
      p: '16px',
      label: '14px',
      subtitle1: '18px',
      caption: '10px',
      captionBold: '10px',
      overline: '12px',
      badge: '12px',
      toggle: '21px', 
      productCardTitle: '24px',
      productCardPrice: '20px',
    },
    lineHeights: {
      h1: '80px',
      h2: '60px',
      h3: '42px',
      h4: '32px',
      h5: '28px',
      h6: '24px',
      p: '24px',
      label: '20px',
      subtitle1: '24px',
      caption: '14px',
      captionBold: '14px',
      overline: '18px',
      badge: '14px',
    },
    spacing: {
      xs: '4px',
      sm: '8px',
      md: '16px',
      lg: '24px',
      xl: '32px',
      toggleGap: '2px',  
    },
    borderRadius: '4px',
  
  sizes: {
    buttonHeight: '40px',
    buttonPadding: '16px',
    checkbox: '16px',
    cardWidth: '300px',
    cardHeight: '400px',
    toggleWidth: '50px',  
    toggleHeight: '25px',
    spinnerSize: '40px'
  },
  grid: {
    columns: {
      default: 'repeat(3, 1fr)',
    },
    gap: {
      sm: '8px',
      md: '16px',
      lg: '24px',
    },
  },
  flex: {
    justifyContent: {
      center: 'center',
      start: 'flex-start',
      end: 'flex-end',
      between: 'space-between',
      around: 'space-around',
    },
    alignItems: {
      center: 'center',
      start: 'flex-start',
      end: 'flex-end',
      stretch: 'stretch',
    },
    direction: {
      row: 'row',
      column: 'column',
    },
    shadows: {
      card: '0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)',
    },
  },
};
  